export { default as About } from "../SVComponents/About/About";
export { default as Accordian } from "../SVComponents/Accordian/Accordian";
export { default as Blog } from "../SVComponents/Blog/Blog";
export { default as Button } from "../SVComponents/Button/Button";
export { default as Contact } from "../SVComponents/Contact/Contact";
export { default as Countries } from "../SVComponents/Countries/Countries";
export { default as Expertise } from "../SVComponents/Expertise/Expertise";
export { default as Feedback } from "../SVComponents/Feedback/Feedback";
export { default as Footer } from "../SVComponents/Footer/Footer";
export { default as Hero } from "../SVComponents/Hero/Hero";
export { default as Institution } from "../SVComponents/Institutions/Institution";
export { default as Navbar } from "../SVComponents/Navbar/Navbar";
export { default as Popular } from "../SVComponents/Popular/Popular";
export { default as Services } from "../SVComponents/Services/Services";
export { default as SmallSec } from "../SVComponents/Small Section/SmallSec";
export { default as Stats } from "../SVComponents/Statistics/Stats";
